# Generated by Django 4.1.1 on 2022-09-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrationpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
