# Generated by Django 4.1.1 on 2022-10-12 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrationpanel",
            "0002_adminuser_is_student_adminuser_is_teacher_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="AdmissionNum",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Blood",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Contact",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="DOB",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Division",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Firstname",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Gender",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Lastname",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Name",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Religion",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="RollNumber",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Std",
            field=models.IntegerField(default=0),
        ),
    ]
