# Generated by Django 4.1.1 on 2022-10-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrationpanel", "0003_adminuser_admissionnum_adminuser_blood_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminuser",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="Password",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="Username",
        ),
        migrations.AddField(
            model_name="adminuser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
