# Generated by Django 4.1.1 on 2022-10-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrationpanel", "0005_alter_adminuser_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="JoinDate",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Salary",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="Subject",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="WorkExperience",
            field=models.IntegerField(default=0),
        ),
    ]
