# Generated by Django 4.1.1 on 2022-10-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrationpanel", "0007_studentfee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentfee",
            name="PaidFee",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentfee",
            name="PendingFee",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentfee",
            name="TotalFee",
            field=models.IntegerField(default=0),
        ),
    ]
