# Generated by Django 4.1.1 on 2022-10-29 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrationpanel",
            "0008_alter_studentfee_paidfee_alter_studentfee_pendingfee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfee",
            name="adminuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
