# Generated by Django 4.1.1 on 2022-10-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrationpanel", "0009_studentfee_adminuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentfee",
            name="adminuser",
        ),
        migrations.AddField(
            model_name="adminuser",
            name="studentfee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrationpanel.studentfee",
            ),
        ),
    ]
