# Generated by Django 4.1.1 on 2022-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrationpanel",
            "0010_remove_studentfee_adminuser_adminuser_studentfee",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminuser",
            name="studentfee",
        ),
        migrations.AddField(
            model_name="studentfee",
            name="AdmissionNum",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="Contact",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="Division",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="Name",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="Std",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
