# Generated by Django 4.1.1 on 2022-10-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrationpanel",
            "0011_remove_adminuser_studentfee_studentfee_admissionnum_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentfee",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="studentfee",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="studentfee",
            name="is_student",
        ),
        migrations.RemoveField(
            model_name="studentfee",
            name="is_teacher",
        ),
    ]
