# Generated by Django 4.1.1 on 2022-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrationpanel", "0012_remove_studentfee_is_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachersSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField(default="", max_length=100)),
                ("Salary", models.BigIntegerField(default=0)),
            ],
        ),
    ]
