# Generated by Django 4.1.1 on 2022-09-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.TextField(max_length=100)),
                ("Email", models.TextField(max_length=100)),
                ("Password", models.TextField(max_length=100)),
                ("is_student", models.BooleanField(default=True)),
            ],
        ),
    ]
