# Generated by Django 4.1.1 on 2022-09-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentUser",
        ),
    ]
